package com.bankorganizer;

import com.google.common.collect.ImmutableSet;
import net.runelite.api.ItemID;

import java.util.Set;

/**
 * Curated sets of item IDs that can be stored in various locations outside the bank.
 * These sets cover the most commonly banked variants; they are not exhaustive.
 */
public final class StorableItems
{
	private StorableItems() {}

	/** Items storable in the Farming Guild seed vault. */
	public static final Set<Integer> SEED_VAULT = ImmutableSet.of(
		// Allotment seeds
		ItemID.POTATO_SEED, ItemID.ONION_SEED, ItemID.CABBAGE_SEED,
		ItemID.TOMATO_SEED, ItemID.SWEETCORN_SEED, ItemID.STRAWBERRY_SEED,
		ItemID.WATERMELON_SEED, ItemID.SNAPE_GRASS_SEED,
		// Herb seeds
		ItemID.GUAM_SEED, ItemID.MARRENTILL_SEED, ItemID.TARROMIN_SEED,
		ItemID.HARRALANDER_SEED, ItemID.RANARR_SEED, ItemID.TOADFLAX_SEED,
		ItemID.IRIT_SEED, ItemID.AVANTOE_SEED, ItemID.KWUARM_SEED,
		ItemID.SNAPDRAGON_SEED, ItemID.CADANTINE_SEED, ItemID.LANTADYME_SEED,
		ItemID.DWARF_WEED_SEED, ItemID.TORSTOL_SEED,
		// Flower seeds
		ItemID.MARIGOLD_SEED, ItemID.ROSEMARY_SEED, ItemID.NASTURTIUM_SEED,
		ItemID.WOAD_SEED, ItemID.LIMPWURT_SEED, ItemID.WHITE_LILY_SEED,
		// Hop seeds
		ItemID.BARLEY_SEED, ItemID.HAMMERSTONE_SEED, ItemID.ASGARNIAN_SEED,
		ItemID.JUTE_SEED, ItemID.YANILLIAN_SEED, ItemID.KRANDORIAN_SEED,
		ItemID.WILDBLOOD_SEED,
		// Tree seeds
		ItemID.ACORN, ItemID.WILLOW_SEED, ItemID.MAPLE_SEED,
		ItemID.YEW_SEED, ItemID.MAGIC_SEED,
		// Fruit tree seeds
		ItemID.APPLE_TREE_SEED, ItemID.BANANA_TREE_SEED, ItemID.ORANGE_TREE_SEED,
		ItemID.CURRY_TREE_SEED, ItemID.PINEAPPLE_SEED, ItemID.PAPAYA_TREE_SEED,
		ItemID.PALM_TREE_SEED, ItemID.DRAGONFRUIT_TREE_SEED,
		// Bush seeds
		ItemID.REDBERRY_SEED, ItemID.CADAVABERRY_SEED, ItemID.DWELLBERRY_SEED,
		ItemID.JANGERBERRY_SEED, ItemID.WHITEBERRY_SEED, ItemID.POISON_IVY_SEED,
		// Special seeds
		ItemID.MUSHROOM_SPORE, ItemID.BELLADONNA_SEED, ItemID.CACTUS_SEED,
		ItemID.POTATO_CACTUS_SEED,
		ItemID.CALQUAT_TREE_SEED, ItemID.TEAK_SEED, ItemID.MAHOGANY_SEED,
		ItemID.SPIRIT_SEED, ItemID.CELASTRUS_SEED, ItemID.REDWOOD_TREE_SEED,
		ItemID.HESPORI_SEED, ItemID.KRONOS_SEED, ItemID.IASOR_SEED,
		ItemID.ATTAS_SEED,
		// Saplings
		ItemID.OAK_SAPLING, ItemID.WILLOW_SAPLING, ItemID.MAPLE_SAPLING,
		ItemID.YEW_SAPLING, ItemID.MAGIC_SAPLING,
		ItemID.APPLE_SAPLING, ItemID.BANANA_SAPLING, ItemID.ORANGE_SAPLING,
		ItemID.CURRY_SAPLING, ItemID.PINEAPPLE_SAPLING, ItemID.PAPAYA_SAPLING,
		ItemID.PALM_SAPLING, ItemID.DRAGONFRUIT_SAPLING,
		ItemID.TEAK_SAPLING, ItemID.MAHOGANY_SAPLING,
		ItemID.CALQUAT_SAPLING, ItemID.SPIRIT_SAPLING,
		ItemID.CELASTRUS_SAPLING, ItemID.REDWOOD_SAPLING
	);

	/** Items storable in the Player-Owned House costume room and other POH storage. */
	public static final Set<Integer> POH_STORAGE = ImmutableSet.of(
		// Capes / cloaks
		ItemID.FIRE_CAPE, ItemID.INFERNAL_CAPE, ItemID.IMBUED_SARADOMIN_CAPE,
		ItemID.IMBUED_GUTHIX_CAPE, ItemID.IMBUED_ZAMORAK_CAPE,
		ItemID.ARDOUGNE_CLOAK_1, ItemID.ARDOUGNE_CLOAK_2,
		ItemID.ARDOUGNE_CLOAK_3, ItemID.ARDOUGNE_CLOAK_4,
		// Achievement diary gear
		ItemID.EXPLORERS_RING_1, ItemID.EXPLORERS_RING_2,
		ItemID.EXPLORERS_RING_3, ItemID.EXPLORERS_RING_4,
		ItemID.FALADOR_SHIELD_1, ItemID.FALADOR_SHIELD_2,
		ItemID.FALADOR_SHIELD_3, ItemID.FALADOR_SHIELD_4,
		ItemID.FREMENNIK_SEA_BOOTS_1, ItemID.FREMENNIK_SEA_BOOTS_2,
		ItemID.FREMENNIK_SEA_BOOTS_3, ItemID.FREMENNIK_SEA_BOOTS_4,
		ItemID.KANDARIN_HEADBAND_1, ItemID.KANDARIN_HEADBAND_2,
		ItemID.KANDARIN_HEADBAND_3, ItemID.KANDARIN_HEADBAND_4,
		ItemID.DESERT_AMULET_1, ItemID.DESERT_AMULET_2,
		ItemID.DESERT_AMULET_3, ItemID.DESERT_AMULET_4,
		ItemID.MORYTANIA_LEGS_1, ItemID.MORYTANIA_LEGS_2,
		ItemID.MORYTANIA_LEGS_3, ItemID.MORYTANIA_LEGS_4,
		ItemID.WESTERN_BANNER_1, ItemID.WESTERN_BANNER_2,
		ItemID.WESTERN_BANNER_3, ItemID.WESTERN_BANNER_4,
		ItemID.WILDERNESS_SWORD_1, ItemID.WILDERNESS_SWORD_2,
		ItemID.WILDERNESS_SWORD_3, ItemID.WILDERNESS_SWORD_4,
		ItemID.KARAMJA_GLOVES_1, ItemID.KARAMJA_GLOVES_2,
		ItemID.KARAMJA_GLOVES_3, ItemID.KARAMJA_GLOVES_4,
		ItemID.LUMBRIDGE_RING_1, ItemID.LUMBRIDGE_RING_2,
		ItemID.LUMBRIDGE_RING_3, ItemID.LUMBRIDGE_RING_4,
		// Treasure trail items (commonly stored)
		ItemID.RANGER_BOOTS, ItemID.HOLY_SANDALS, ItemID.WIZARD_BOOTS,
		// Holiday items
		ItemID.SANTA_HAT, ItemID.RED_HWEEN_MASK, ItemID.GREEN_HWEEN_MASK,
		ItemID.BLUE_HWEEN_MASK, ItemID.EASTER_EGG, ItemID.PUMPKIN,
		ItemID.CHRISTMAS_CRACKER,
		// Quest items often stored
		ItemID.HELM_OF_NEITIZNOT
	);

	/** Items storable in potion storage (unlocked via Nex). */
	public static final Set<Integer> POTION_STORAGE = ImmutableSet.of(
		// Standard potions (4-dose as primary; the plugin matches all doses via name)
		ItemID.ATTACK_POTION4, ItemID.ATTACK_POTION3, ItemID.ATTACK_POTION2, ItemID.ATTACK_POTION1,
		ItemID.STRENGTH_POTION4, ItemID.STRENGTH_POTION3, ItemID.STRENGTH_POTION2, ItemID.STRENGTH_POTION1,
		ItemID.DEFENCE_POTION4, ItemID.DEFENCE_POTION3, ItemID.DEFENCE_POTION2, ItemID.DEFENCE_POTION1,
		ItemID.PRAYER_POTION4, ItemID.PRAYER_POTION3, ItemID.PRAYER_POTION2, ItemID.PRAYER_POTION1,
		ItemID.SUPER_ATTACK4, ItemID.SUPER_ATTACK3, ItemID.SUPER_ATTACK2, ItemID.SUPER_ATTACK1,
		ItemID.SUPER_STRENGTH4, ItemID.SUPER_STRENGTH3, ItemID.SUPER_STRENGTH2, ItemID.SUPER_STRENGTH1,
		ItemID.SUPER_DEFENCE4, ItemID.SUPER_DEFENCE3, ItemID.SUPER_DEFENCE2, ItemID.SUPER_DEFENCE1,
		ItemID.RANGING_POTION4, ItemID.RANGING_POTION3, ItemID.RANGING_POTION2, ItemID.RANGING_POTION1,
		ItemID.MAGIC_POTION4, ItemID.MAGIC_POTION3, ItemID.MAGIC_POTION2, ItemID.MAGIC_POTION1,
		ItemID.SUPER_RESTORE4, ItemID.SUPER_RESTORE3, ItemID.SUPER_RESTORE2, ItemID.SUPER_RESTORE1,
		ItemID.SARADOMIN_BREW4, ItemID.SARADOMIN_BREW3, ItemID.SARADOMIN_BREW2, ItemID.SARADOMIN_BREW1,
		ItemID.ANTIFIRE_POTION4, ItemID.ANTIFIRE_POTION3, ItemID.ANTIFIRE_POTION2, ItemID.ANTIFIRE_POTION1,
		ItemID.SUPER_ANTIFIRE_POTION4, ItemID.SUPER_ANTIFIRE_POTION3, ItemID.SUPER_ANTIFIRE_POTION2, ItemID.SUPER_ANTIFIRE_POTION1,
		ItemID.ANTIDOTE4_5952, ItemID.ANTIDOTE3, ItemID.ANTIDOTE2, ItemID.ANTIDOTE1,
		ItemID.STAMINA_POTION4, ItemID.STAMINA_POTION3, ItemID.STAMINA_POTION2, ItemID.STAMINA_POTION1,
		ItemID.EXTENDED_ANTIFIRE4, ItemID.EXTENDED_ANTIFIRE3, ItemID.EXTENDED_ANTIFIRE2, ItemID.EXTENDED_ANTIFIRE1,
		ItemID.EXTENDED_SUPER_ANTIFIRE4, ItemID.EXTENDED_SUPER_ANTIFIRE3, ItemID.EXTENDED_SUPER_ANTIFIRE2, ItemID.EXTENDED_SUPER_ANTIFIRE1,
		ItemID.DIVINE_SUPER_ATTACK_POTION4, ItemID.DIVINE_SUPER_ATTACK_POTION3, ItemID.DIVINE_SUPER_ATTACK_POTION2, ItemID.DIVINE_SUPER_ATTACK_POTION1,
		ItemID.DIVINE_SUPER_STRENGTH_POTION4, ItemID.DIVINE_SUPER_STRENGTH_POTION3, ItemID.DIVINE_SUPER_STRENGTH_POTION2, ItemID.DIVINE_SUPER_STRENGTH_POTION1,
		ItemID.DIVINE_SUPER_DEFENCE_POTION4, ItemID.DIVINE_SUPER_DEFENCE_POTION3, ItemID.DIVINE_SUPER_DEFENCE_POTION2, ItemID.DIVINE_SUPER_DEFENCE_POTION1,
		ItemID.DIVINE_RANGING_POTION4, ItemID.DIVINE_RANGING_POTION3, ItemID.DIVINE_RANGING_POTION2, ItemID.DIVINE_RANGING_POTION1,
		ItemID.DIVINE_MAGIC_POTION4, ItemID.DIVINE_MAGIC_POTION3, ItemID.DIVINE_MAGIC_POTION2, ItemID.DIVINE_MAGIC_POTION1,
		ItemID.DIVINE_SUPER_COMBAT_POTION4, ItemID.DIVINE_SUPER_COMBAT_POTION3, ItemID.DIVINE_SUPER_COMBAT_POTION2, ItemID.DIVINE_SUPER_COMBAT_POTION1,
		ItemID.DIVINE_BASTION_POTION4, ItemID.DIVINE_BASTION_POTION3, ItemID.DIVINE_BASTION_POTION2, ItemID.DIVINE_BASTION_POTION1,
		ItemID.DIVINE_BATTLEMAGE_POTION4, ItemID.DIVINE_BATTLEMAGE_POTION3, ItemID.DIVINE_BATTLEMAGE_POTION2, ItemID.DIVINE_BATTLEMAGE_POTION1,
		ItemID.SUPER_COMBAT_POTION4, ItemID.SUPER_COMBAT_POTION3, ItemID.SUPER_COMBAT_POTION2, ItemID.SUPER_COMBAT_POTION1,
		ItemID.BASTION_POTION4, ItemID.BASTION_POTION3, ItemID.BASTION_POTION2, ItemID.BASTION_POTION1,
		ItemID.BATTLEMAGE_POTION4, ItemID.BATTLEMAGE_POTION3, ItemID.BATTLEMAGE_POTION2, ItemID.BATTLEMAGE_POTION1
	);

	/** Items storable in the Varrock Museum fossil storage. */
	public static final Set<Integer> FOSSIL_STORAGE = ImmutableSet.of(
		ItemID.SMALL_FOSSIL, ItemID.MEDIUM_FOSSIL, ItemID.LARGE_FOSSIL,
		ItemID.RARE_FOSSIL, ItemID.UNIDENTIFIED_SMALL_FOSSIL,
		ItemID.UNIDENTIFIED_MEDIUM_FOSSIL, ItemID.UNIDENTIFIED_LARGE_FOSSIL,
		ItemID.UNIDENTIFIED_RARE_FOSSIL
	);
}
